### ISSUE TITLE
MZRME'S

### ISSUE THREAD

**Issue by imzrme** [JohnsonRan/friends-api#2]
```json
{
    "title": "MZRME'S",
    "url": "https://mzrme.com",
    "avatar": "https://mzrme.com/logo.webp",
    "screenshot": "",
    "description": "You're the Miracles."
}
```

issue友链仓库（没有请忽略）： https://

**Comment by JohnsonRan** [comment]
请将 avatar 链接改为你的博客图标

**Comment by imzrme** [comment]
> 请将 avatar 链接改为你的博客图标

{
    "title": "MZRME'S",
    "url": "https://mzrme.com",
    "avatar": "https://mzrme.com/logo.webp",
    "screenshot": "",
    "description": "You're the Miracles."
}

**Comment by JohnsonRan** [comment]
博客已经打不开了
